apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app  : my-k8s-appliation
    env  : prod
    owner: ilia
spec:
  replicas: 3
  selector:
    mathcLabels:
      project: laravel
  template:
    metadata:
      project: laravel
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:10.2
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
          - MARIADB_USER=my_user
          - MARIADB_DATABASE=my_database
          - MARIADB_PASSWORD=my_password
      - name: myapp
        tty: true
        image: bitnami/laravel:8
        environment:
          - DB_HOST=mariadb
          - DB_USERNAME=my_user
          - DB_DATABASE=my_database
          - DB_PASSWORD=my_password
        depends_on:
          - mariadb
        volumes:
          - ./:/app
        ports:
          containerPort: 3000
