apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-appliation
spec:
  selector:
    matchLabels: 
      project: kgb
  template:
    metadata:
      project: kgb
    spec:
      containers:
      - name: kgb-web
        image: adv4000/k8sphp:version1
        ports:
          containerPort: 80
