apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
    - port: 3000
  selector:
    app: myapp
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - image: bitnami/laravel:8
        name: myapp
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PASSWORD
          value: ""
        ports:
        - containerPort: 3000
          name: myapp
        volumeMounts:
        - name: myapp-persistent-storage
          mountPath: ./:/app
      volumes:
      - name: myapp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
